spring:
  application:
    name: HotelService

  datasource:
    url: jdbc:postgresql://localhost:5432/microservices  # URL of the PostgreSQL database
    username: postgres
    # Your PostgreSQL username
    password: pass@123  # Your PostgreSQL password
    driver-class-name: org.postgresql.Driver  # PostgreSQL driver class name
    hikari:
      maximum-pool-size: 10  # Optional: maximum number of connections in the connection pool

  jpa:
    hibernate:
      ddl-auto: update  # Optional: Controls the schema generation behavior
    show-sql: true  # Optional: Show SQL queries in the log
#    database-platform: org.hibernate.dialect.PostgreSQLDialect  # PostgreSQL dialect for Hibernate

server:
  port: 9090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # URL of your Eureka server
    register-with-eureka: true  # Ensures that the service registers itself
    fetch-registry: true  # Allows the service to fetch the registry information
